#!/bin/sh

install_file()
{
	src="$1"
	dest="$2"

	if [ ! -e "$dest" ]
	then
		cp "$src" "${dest}"
		return 1
	else
		echo "Service file already exists, skip creation"
		return 0
	fi
}


echo "Finalizing Ambilight App setup"

#check system
CPU_RPI=`grep -m1 -c 'BCM2708\|BCM2709\|BCM2710\|BCM2835\|BCM2836\|BCM2837\|BCM2711' /proc/cpuinfo`
CPU_X32X64=`uname -m | grep 'x86_32\|i686\|x86_64' | wc -l`

#Check for a bootloader as Berryboot
BOOT_BERRYBOOT=$(grep -m1 -c '\(/var/media\|/media/pi\)/berryboot' /etc/mtab)

#get current system ip
NET_IP=`hostname -I | cut -d " " -f1`

# search for users in system, returns first entry
FOUND_USR=`who | grep -o -m1 '^\w*\b'` || "root"

# determine if we should use a service
ENABLE_XSYS=0
ENABLE_SERVICE=0
STARTUP_MSG="Service is NOT enabled by default for GUI or non-systemd OS"

if [ $CPU_RPI -eq 1 ]; then
	ENABLE_SERVICE=1
	STARTUP_MSG="Ambilight App is installed as a service and starts automatically"
fi

start_msg=""
restart_msg=""

echo "Extracting LUT table..."
tar -xf /usr/share/ambilightapp/lut/lut_lin_tables.tar.xz -C /usr/share/ambilightapp/lut/
rm -f -v /usr/share/ambilightapp/lut/lut_lin_tables.tar.xz

if grep -m1 systemd /proc/1/comm > /dev/null
then	
	# systemd
	if [ -z "${DISPLAY}" ]; then
		echo "Ambilight App is installed as a service and starts automatically"
		ENABLE_SERVICE=1
	else
		echo "Init daemon: GUI detected (service is NOT enabled by default, you can run Ambilight App as an application or service with 'systemctl enable (and next: start) ambilightapp@${FOUND_USR}.service')"
		ENABLE_SERVICE=0
		ENABLE_XSYS=1
	fi
	
	install_file /usr/share/ambilightapp/service/ambilightapp.systemd /etc/systemd/system/ambilightapp@.service	

	if [ $ENABLE_SERVICE -eq 1 ]; then
		systemctl enable ambilightapp"@${FOUND_USR}".service
		start_msg="systemctl start ambilightapp for user ${FOUND_USR}"
		systemctl start ambilightapp"@${FOUND_USR}"
	fi

elif [ -e /sbin/initctl ]
then	
	# upstart
	if [ $ENABLE_SERVICE -eq 1 ]; then
		echo "Init daemon: upstart (service is enabled by default)"
		install_file /usr/share/ambilightapp/service/ambilightapp.initctl /etc/init/ambilightapp.conf && initctl reload-configuration
		start_msg="initctl start ambilightapp"
		initctl start ambilightapp
	else
		echo "Init daemon: upstart (service is NOT enabled by default)"
	fi

else	
	# sysV
	if [ $ENABLE_SERVICE -eq 1 ]; then
		echo "Init daemon: sysV (enabled by default)"
		install_file /usr/share/ambilightapp/service/ambilightapp.init /etc/init.d/ambilightapp && chmod +x /etc/init.d/ambilightapp && update-rc.d ambilightapp defaults 98 02
		start_msg="service ambilightapp start"
		service ambilightapp start
	else
		echo "Init daemon: sysV (service is NOT enabled by default)"
	fi
fi

#cleanup
rm -r /usr/share/ambilightapp/service

#link binarys and set exec bit
BINSP=/usr/share/ambilightapp/bin
BINTP=/usr/bin
chmod +x -R $BINSP
ln -fs $BINSP/ambilightapp $BINTP/ambilightapp
ln -fs $BINSP/ambilightapp-remote $BINTP/ambilightapp-remote

# install desktop icons
echo "Install Ambilight App desktop icons"
mkdir /usr/share/pixmaps/ambilightapp 2>/dev/null
cp /usr/share/ambilightapp/desktop/*.png /usr/share/pixmaps/ambilightapp 2>/dev/null
desktop-file-install /usr/share/ambilightapp/desktop/ambilightapp.desktop 2>/dev/null

# cleanup desktop icons
rm -r /usr/share/ambilightapp/desktop 2>/dev/null

#Check, if dtparam=spi=on is in place
if [ $CPU_RPI -eq 1 ]; then
	BOOT_DIR="/boot"
	if [ $BOOT_BERRYBOOT -eq 1 ]; then
		BOOT_DIR=$(sed -ne "s#/dev/mmcblk0p1 \([^ ]*\) vfat rw,.*#\1#p" /etc/mtab)
	fi
	if [ -z "$BOOT_DIR" -o ! -f "$BOOT_DIR/config.txt" ]; then
		echo 'Warning: RPi using BERRYBOOT found but can not locate where config.txt is to enable SPI. (BOOT_DIR='"$BOOT_DIR)"
		SPIOK=1 # Not sure if OK, but don't ask to reboot
	else
		SPIOK=`grep '^\dtparam=spi=on' "$BOOT_DIR/config.txt" | wc -l`
		if [ $SPIOK -ne 1 ]; then
			echo 'Raspberry Pi found, but SPI is not set, we write "dtparam=spi=on" to '"$BOOT_DIR/config.txt"
			sed -i '$a dtparam=spi=on' "$BOOT_DIR/config.txt"
			REBOOTMESSAGE="Restart Raspberry Pi, SPI has been enabled in $BOOT_DIR/config.txt"
		fi
	fi
fi

echo ${start_msg}

echo " +-----------------------------------------------------------------------+"
echo " |                 \033[32;1mAmbilight App has been installed/updated!\033[0m                  |"
echo " +-----------------------------------------------------------------------+"
printf " |  For configuration, visit with your browser: \033[37;1m%13s:%s\033[0m       |\n" "$NET_IP" "8090"
printf " |  If already used by another service try: \033[37;1m%13s:%s\033[0m           |\n" "$NET_IP" "8091"
printf " |  Start the service: \033[37;1msudo systemctl start ambilightapp@%-12s\033[0m        |\n" "$FOUND_USR"
printf " |  Stop the service: \033[37;1msudo systemctl stop ambilightapp@%-12s\033[0m          |\n" "$FOUND_USR"
echo   " |  Troubleshooting? Run Ambilight App manually: \033[37;1m/usr/bin/ambilightapp\033[0m            |"
echo   " +-----------------------------------------------------------------------+"
case "$STARTUP_MSG" in 
  *"Ambilight App is installed as a service"*)
	printf " |  \033[32;1m%-67s\033[0m  |\n" "$STARTUP_MSG";;
  *) printf " |  \033[31;1m%-67s\033[0m  |\n" "$STARTUP_MSG"
esac
[ -z "$REBOOTMESSAGE" ] || printf " |  \033[31;1m%-67s\033[0m  |\n" "$REBOOTMESSAGE"
echo " +-----------------------------------------------------------------------+"
echo " |  Webpage: \033[36;1mhttp://ambilightled.com\033[0m                                         |"
echo " |  GitHub: \033[36;1mhttp://ambilightled.com\033[0m                        |"
echo " +-----------------------------------------------------------------------+"

exit 0
